# Generated by Django 4.2.4 on 2023-08-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatorset',
            name='GeneratorSet',
        ),
        migrations.RemoveField(
            model_name='generatorset',
            name='buyers',
        ),
        migrations.AddField(
            model_name='generatorset',
            name='generators',
            field=models.ManyToManyField(related_name='generator_sets', to='relationship.generator'),
        ),
    ]
